server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.h2.Driver
    schema: classpath:db/schema-h2.sql
#    data: classpath:db/data-h2.sql
    url: jdbc:h2:mem:test
    username: sa
    password:

  redis:
    host: localhost
    port: 6379

mybatis-plus:
  mapper-locations:
    - classpath:/mapper/*Mapper.xml
  global-config:
    db-config:
      capital-mode: true
      id-type: assign_id
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

crawl:
#  site: douban
  site: google

logging:
  level:
    org.apache.ibatis: debug
    com.baomidou.mybatisplus: debug
